site_name: Westworld Documentation
site_description: 'Multi-agent simulation library'
site_author: 'UnityGrid Al's Westworld
site_url: "https://UnityGrid.AI/westworld"
edit_uri: ""
theme:
  name: 'material'
  font:
    text: Inter
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
repo_name: 'unitygrid/westworld'
repo_url: 'https://github.com/unitygrid/westworld'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheoLvs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/theolvsdc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/th%C3%A9o-alves-da-costa-09397a82/


extra_css:
  - ./stylesheets/extra.css

nav:
  - Home: 
    - Home: index.md
    - References: references.md
    - Changelog: changelog.md
  - Tutorials:
    - Basic:
      - Quickstart: tutorials/quickstart.md
      - Movements: tutorials/movements.md
      - Objects: tutorials/objects.md
    - Extra features: 
      - Maze generation: tutorials/maze.md
      - Other: tutorials/other.md
  - API:
    - api/index.md